### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by ghost** [jebster-pagekit/maps#1]
When I installed the extension it breaks the whole template and removes much of my head

![image](https://cloud.githubusercontent.com/assets/16963836/23568641/312a94ba-003a-11e7-98c4-b93289a15dab.png)

**Comment by ghost** [comment]
It was solved when I put a height and width. Maybe it should indicate that this field are oblibligatory.

**Comment by jeggy** [comment]
yeah sorry. Maybe I should put some validation on that. Will do that in the next update ;)

**Comment by jeggy** [comment]
There, I just added default values for it ;)

**Comment by ghost** [comment]
Great! thanks
